-- DropIndex
DROP INDEX "public"."RefreshToken_userId_isRevoked_idx";

-- DropIndex
DROP INDEX "public"."Role_name_tenant_idx";

-- DropIndex
DROP INDEX "public"."User_email_isDeleted_idx";

-- AlterTable
ALTER TABLE "AuditLog" ALTER COLUMN "action" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "resource" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "method" SET DATA TYPE VARCHAR(10),
ALTER COLUMN "path" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "statusCode" SET DATA TYPE SMALLINT,
ALTER COLUMN "ipAddress" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "userAgent" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Permission" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "resource" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "action" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "category" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "RefreshToken" ALTER COLUMN "token" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "deviceInfo" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "ipAddress" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "revokedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "revokedReason" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "type" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "level" SET DATA TYPE SMALLINT,
ALTER COLUMN "status" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "deviceInfo" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "ipAddress" SET DATA TYPE VARCHAR(45),
ALTER COLUMN "userAgent" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "lastActivity" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "logo" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "website" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "subscriptionPlan" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "subscriptionStatus" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "subscriptionExpiry" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "maxUsers" SET DATA TYPE SMALLINT,
ALTER COLUMN "status" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "password" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20),
ALTER COLUMN "avatar" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "emailVerificationToken" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "passwordResetToken" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "passwordResetExpiry" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "lastLogin" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "loginAttempts" SET DATA TYPE SMALLINT,
ALTER COLUMN "lockedUntil" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "status" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "deletedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

